spring.application.name=devops-user

# Change server port
server.port=8081


spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.initialization-mode=always
spring.datasource.platform=postgres
spring.datasource.url=jdbc:postgresql://postgres:5432/devops_db
spring.datasource.username=postgres
spring.datasource.password=postgres


#https://stackoverflow.com/questions/43905119/postgres-error-method-org-postgresql-jdbc-pgconnection-createclob-is-not-imple
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql

spring.jpa.open-in-view=true

#optimizacija za postgres upite
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include=health, info, metrics, prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.observations.key-values.application=devops-user

management.tracing.sampling.probability=1.0
management.tracing.enabled=true

management.zipkin.tracing.endpoint=http://tempo:9411/api/v2/spans

logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]