CREATE TABLE IF NOT EXISTS test_table (
    id INT PRIMARY KEY,
    name VARCHAR(255)
);

-- Create table for addresses
CREATE TABLE IF NOT EXISTS addresses_test (
        id integer generated by default as identity,
        number_of_building integer,
        city varchar(255) not null,
        country varchar(255) not null,
        street varchar(255) not null,
        primary key (id)
);

-- Create table for users
 CREATE TABLE IF NOT EXISTS users_test (
        address_id integer,
        deleted boolean not null,
        id integer generated by default as identity,
        email varchar(255) not null unique,
        first_name varchar(255) not null,
        last_name varchar(255) not null,
        password varchar(255) not null,
        role varchar(255) not null check (role in ('HOST','GUEST')),
        username varchar(255) not null unique,
        primary key (id)
    )

--  ALTER TABLE users_test
--   ADD CONSTRAINT fk_users_test_address_id
--   FOREIGN KEY (address_id) REFERENCES addresses_test(id)
--   ON DELETE CASCADE;

-- Insert sample data
--INSERT INTO addresses_test (street, number_of_building, city, country)
--VALUES ('Main Street', 101, 'New York', 'USA');
--
--INSERT INTO users_test (first_name, last_name, username, password, email, role, deleted, address_id)
--VALUES ('John', 'Doe', 'johndoe', '$2a$10$X7F3hUST4aTxWHikNRY7gek7xsjW352cF51QmbRehvE9rGJooAMhW', 'johndoe@example.com', 'GUEST', false, 1);
--
--INSERT INTO rates_test (rate, date, host_id, guest_id)
--VALUES (4, '2024-12-19T10:00:00', 16, 1);
